// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/skamranahmed/go-bank/pkg/tasks (interfaces: TaskEnqueuer)
//
// Generated by this command:
//
//	mockgen -package mock -destination mock/asynq_task_enqueuer.go github.com/skamranahmed/go-bank/pkg/tasks TaskEnqueuer
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	tasks "github.com/skamranahmed/go-bank/pkg/tasks"
	gomock "go.uber.org/mock/gomock"
)

// MockTaskEnqueuer is a mock of TaskEnqueuer interface.
type MockTaskEnqueuer struct {
	ctrl     *gomock.Controller
	recorder *MockTaskEnqueuerMockRecorder
	isgomock struct{}
}

// MockTaskEnqueuerMockRecorder is the mock recorder for MockTaskEnqueuer.
type MockTaskEnqueuerMockRecorder struct {
	mock *MockTaskEnqueuer
}

// NewMockTaskEnqueuer creates a new mock instance.
func NewMockTaskEnqueuer(ctrl *gomock.Controller) *MockTaskEnqueuer {
	mock := &MockTaskEnqueuer{ctrl: ctrl}
	mock.recorder = &MockTaskEnqueuerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskEnqueuer) EXPECT() *MockTaskEnqueuerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockTaskEnqueuer) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockTaskEnqueuerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockTaskEnqueuer)(nil).Close))
}

// Enqueue mocks base method.
func (m *MockTaskEnqueuer) Enqueue(ctx context.Context, task tasks.Task, maxRetryCount *int, queueName *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enqueue", ctx, task, maxRetryCount, queueName)
	ret0, _ := ret[0].(error)
	return ret0
}

// Enqueue indicates an expected call of Enqueue.
func (mr *MockTaskEnqueuerMockRecorder) Enqueue(ctx, task, maxRetryCount, queueName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enqueue", reflect.TypeOf((*MockTaskEnqueuer)(nil).Enqueue), ctx, task, maxRetryCount, queueName)
}
