FROM golang:1.25.1-alpine3.21

RUN apk add --no-cache make

WORKDIR /app

COPY ./migrator/go.mod ./migrator/go.sum ./
RUN go mod download

COPY ./Makefile ./
COPY ./migrator ./migrator

CMD ["make", "migrate-up"]